const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('bm', {
  gpu:    () => ipcRenderer.invoke('gpu:stats'),
  power:  (w, i) => ipcRenderer.invoke('power:set', w, i),
  powerReset: (i) => ipcRenderer.invoke('power:reset', i),
  pickMiner: () => ipcRenderer.invoke('miner:pick'),
  start:  (p) => ipcRenderer.invoke('miner:start', p),
  stop:   () => ipcRenderer.invoke('miner:stop'),
  downloadMiner: () => ipcRenderer.invoke('miner:download'),
  downloadGpuMiner: () => ipcRenderer.invoke('miner:downloadLol'),
  loadCfg: () => ipcRenderer.invoke('config:load'),
  saveCfg: (c) => ipcRenderer.invoke('config:save', c),
  prices: () => ipcRenderer.invoke('prices:fetch'),
  dcInit:  (o) => ipcRenderer.invoke('dc:init', o),
  dcStatus: (s) => ipcRenderer.invoke('dc:status', s),
  dcStop:  () => ipcRenderer.invoke('dc:stop'),
  openExternal: (url) => ipcRenderer.invoke('open:external', url),
  dcReady: (cb) => ipcRenderer.on('dc:ready', (_e, d) => cb(d)),
  dcError: (cb) => ipcRenderer.on('dc:error', (_e, d) => cb(d)),
  dcConnecting: (cb) => ipcRenderer.on('dc:connecting', () => cb()),
  isAdmin: () => ipcRenderer.invoke('sys:admin'),
  elevate: () => ipcRenderer.invoke('sys:elevate'),
  sys:    () => ipcRenderer.invoke('sys:info'),
  updateCheck:    () => ipcRenderer.invoke('update:check'),
  updateDownload: (url) => ipcRenderer.invoke('update:download', url),
  updateInstall:  (installerPath) => ipcRenderer.invoke('update:install', installerPath),
  updateOpen:     (url) => ipcRenderer.invoke('update:open', url),
  onLog:  (cb) => ipcRenderer.on('miner:log', (_e, d) => cb(d)),
  onStop: (cb) => ipcRenderer.on('miner:stopped', () => cb()),
  onData: (cb) => ipcRenderer.on('gpu:data', (_e, d) => cb(d)),
});